apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flight-reservation-backend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/nileshbhurewar/Flight-reservation.git
    targetRevision: main
    path: FlightReservationApplication/k8s/backend

  destination:
    server: https://kubernetes.default.svc
    namespace: flight-reservation

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
